[package]
name = "diff-struct"
version = "0.1.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
edition = "2018"

[lib]
name = "diff"
path = "src/lib.rs"

[dependencies]
diff-derive = { path = "diff-derive" }

[workspace]
members = ["diff-derive"]
