[package]
name = "diff-struct"
description = "A trait for diffing and apply diffs to structs of a certain type"
version = "0.1.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
repository = "https://github.com/BenHall-7/diff-struct"
license = "MIT"
edition = "2018"

[lib]
name = "diff"
path = "src/lib.rs"

[dependencies]
diff_derive = "0.1.0"
